services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/lmorel/data/mariadb
      o: bind
    name: mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lmorel/data/wordpress
      o: bind
    name: wordpress

networks:
  inception:
    driver: bridge
    name : inception
