CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'lmorel'@'%' IDENTIFIED BY '4242';
GRANT ALL PRIVILEGES ON wordpress.* TO 'lmorel'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '4242';